---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
 name: yaml-lint
spec:
  params:
    - name: repo
    type: string
  tasks:
    - - name: clone
      params:
        - name: url
          value: "$(params.repo)"
      taskRef:
  - name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: lint
      runAfter:
        - clone
      taskRef:
        name: yaml-lint
        kind: Task
      workspaces:
        - name: shared-workspace
          workspace: shared-workspace
      params:
        - name: args
          value: ["."]
  workspaces:
    - name: shared-workspace
